from __future__ import annotations

import os

SEED = 108
DATA_SELECTION_SEED = 1108

MODEL_REPOSITORY = "Qwen/Qwen2.5-0.5B"
MODEL_REVISION = "060db6499f32faf8b98477b0a26969ef7d8b9987"
DATASET_REPOSITORY = "trl-lib/Capybara"
DATASET_REVISION = "e235e846458bff3398a88aed812347f7f0756520"

TRAIN_EXAMPLES = 4_096
DEV_EXAMPLES = 512
VALIDATION_EXAMPLES = 1_024
MAX_DOCUMENT_LENGTH = 192
DOCUMENTS_PER_PACK = 4

ADAPTER_RANK = 16
ADAPTER_ALPHA = 32.0
ADAPTER_TARGETS = ("q_proj", "v_proj")

REFERENCE_WORLD_SIZE = 4
WORLD_SIZE = int(os.environ.get("WORLD_SIZE", str(REFERENCE_WORLD_SIZE)))
REFERENCE_GLOBAL_DOCUMENT_BATCH = 16
MICROBATCH_GLOBAL_DOCUMENTS = WORLD_SIZE * DOCUMENTS_PER_PACK
if (
    WORLD_SIZE <= 0
    or REFERENCE_GLOBAL_DOCUMENT_BATCH % MICROBATCH_GLOBAL_DOCUMENTS
):
    raise RuntimeError(
        f"{WORLD_SIZE} ranks with {DOCUMENTS_PER_PACK} documents per rank "
        f"cannot preserve global batch {REFERENCE_GLOBAL_DOCUMENT_BATCH}"
    )
GRADIENT_ACCUMULATION_STEPS = (
    REFERENCE_GLOBAL_DOCUMENT_BATCH // MICROBATCH_GLOBAL_DOCUMENTS
)
GLOBAL_DOCUMENT_BATCH = (
    MICROBATCH_GLOBAL_DOCUMENTS * GRADIENT_ACCUMULATION_STEPS
)
UPDATES = TRAIN_EXAMPLES // GLOBAL_DOCUMENT_BATCH

LEARNING_RATE = 2.0e-4
WEIGHT_DECAY = 0.0
OPTIMIZER_BETAS = (0.9, 0.95)
OPTIMIZER_EPSILON = 1.0e-8
GRADIENT_CLIP = 1.0
WARMUP_UPDATES = 16

EVAL_BATCH_SIZE = 8

assert GLOBAL_DOCUMENT_BATCH == 16
assert UPDATES == 256
